### ISSUE TITLE
Epi.Gadget.MultiSelect.TwoAreas -- code available?

### ISSUE THREAD

**Issue by daniel-isaacs** [Shumigaj/EPiServer-Libraries#1]
Hi, I was just wondering if your code for this was available at all? (Or alternatively, if you've updated it to CMS 12 at all?)
Thanks!
-Dan

**Comment by Shumigaj** [comment]
Dear Dan,

I wanted to provide clarity regarding the licensing of my Epi libraries. Initially, I opted for the Microsoft Public License as it permitted the use of these libraries in commercial products without the requirement of disclosing the source code to the public. While this decision seemed appropriate at that point in my career, I have since come to regret it.

As of now, the source code for the Epi libraries is not available. Regrettably, I'm unable to assist with the release of an update for CMS 12, as my involvement with EpiServer ceased at version 11.

I appreciate your question and thank you for reaching out.

Best regards,
Pavel

**Comment by daniel-isaacs** [comment]
Sounds good, appreciate the response!
